import math
from abc import ABC, abstractmethod
from dataclasses import dataclass

import numpy as np
import numpy.typing as npt
from scipy import special, stats


class Distribution(ABC):
    @abstractmethod
    def sample(
        self, rng: np.random.Generator, size: int = 1
    ) -> npt.NDArray[np.float64]: ...

    @property
    @abstractmethod
    def mean(self) -> float: ...

    # return the mean IAT generated by this distribution

    @abstractmethod
    def residual_q(self, q: float, t: float) -> float: ...

    # return the remaining time for a q% chance of arrival,
    # given time t since last arrival
    # i.e. the delay w that satisfies the conditioned probability
    # Pr(X < t+w | X > t) = q


@dataclass
class Exponential(Distribution):
    scale: float

    def __post_init__(self):
        if not self.scale > 0:
            raise ValueError(f"@Exponential: scale must be positive, got {self.scale}")

    def sample(
        self, rng: np.random.Generator, size: int = 1
    ) -> npt.NDArray[np.float64]:
        return rng.exponential(scale=self.scale, size=size)

    @property
    def mean(self) -> float:
        return self.scale

    def residual_q(self, q: float, t: float) -> float:
        return -np.log(1.0 - q) * self.scale


@dataclass
class Erlang(Distribution):
    scale: float
    k: int
    APPROXIMATE_QUANTILES: bool = False

    def __post_init__(self):
        if not self.scale > 0:
            raise ValueError(f"@Erlang: scale must be positive, got {self.scale}")
        if not self.k > 0:
            raise ValueError(f"@Erlang: count (k) must be positive, got {self.k}")

    def sample(
        self, rng: np.random.Generator, size: int = 1
    ) -> npt.NDArray[np.float64]:
        return rng.gamma(shape=self.k, scale=self.scale, size=size)

    @property
    def mean(self) -> float:
        return self.k * self.scale

    def residual_q(self, q: float, t: float) -> float:
        if self.APPROXIMATE_QUANTILES:
            # TODO quantile approximation, if required
            return 1.0
        else:
            c = (1 - q) * special.gammaincc(self.k, self.scale * t)
            u = special.gammainccinv(self.k, c)
            return u / self.scale - t


@dataclass
class LogNormal(Distribution):
    mu: float
    sigma: float
    APPROXIMATE_QUANTILES: bool = False

    def __post_init__(self):
        if not self.sigma > 0:
            raise ValueError(f"@LogNormal: sigma must be positive, got {self.sigma}")

    def sample(
        self, rng: np.random.Generator, size: int = 1
    ) -> npt.NDArray[np.float64]:
        return rng.lognormal(mean=self.mean, sigma=self.sigma, size=size)

    @property
    def mean(self) -> float:
        return math.exp(self.mu + 0.5 * self.sigma**2)

    def residual_q(self, q: float, t: float) -> float:
        if self.APPROXIMATE_QUANTILES:
            # TODO quantile approximation, if required
            return 1.0
        else:
            return float(
                stats.lognorm.isf(
                    (1 - q)
                    * stats.lognorm.sf(t, s=self.sigma, loc=0, scale=np.exp(self.mu)),
                    s=self.sigma,
                    loc=0,
                    scale=np.exp(self.mu),
                )
                - t
            )
